{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-{{ tpl .Values.serviceAccount.name . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.serviceAccount.name . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
