{{- if $.Values.role.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
  namespace: notebooks
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
{{- end }}
