{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 6 }}
  {{- end }}
  name: {{ tpl .Values.serviceAccount.name . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
